#!/usr/bin/env python

# Calculate stats based on output from dice_lesions.py.

import argparse
import csv
import os
import statistics
import sys

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--dice_lesion_csv", type=str, required=True, nargs="+",
                        help="CSV file generated by dice_lesions.py")
    parser.add_argument("--category", type=int, nargs="+", default=[None],
                        help="Categories to assess (default: nonzero)")
    parser.add_argument("--output_csv", type=str, required=False,
                        help="File to write data (or stdout if not set)")
    args = parser.parse_args()

    # Validate command line arguments.
    for f in args.dice_lesion_csv:
        if not os.path.isfile(f):
            raise ValueError("CSV file does not exist: " + f)

    output_data = [["model", "feature", "mean", "sd", "median", "min", "max"]]

    lesion_stats = {}

    for f in args.dice_lesion_csv:
        lesions = []
        dice_vals = {}
        with open(f, 'r') as csvfile:
            rows = csv.DictReader(csvfile)
            lesions = rows.fieldnames[2:]

            for l in lesions:
                dice_vals[l] = []

            for row in rows:
                pred = int(row["prediction"])
                if args.category == [None]:
                    if pred == 0:
                        continue
                elif pred not in args.category:
                    continue

                for l in lesions:
                    if not l in row or row[l] is None:
                        print(str(l) + " is not in " + f, file=sys.stderr)
                        continue

                    if row[l] not in ("None", ""):
                        dice_vals[l].append(float(row[l]))

        for lesion, vals in dice_vals.items():
            printvals = ["N/A"] * 5
            if len(vals) > 0:
                # Default values when there is only one value.
                printvals = [vals[0], 0]

                if len(vals) != 1:
                    printvals = [statistics.mean(vals),
                                 statistics.stdev(vals)]

                printvals += [statistics.median(vals), min(vals), max(vals)]

                if not lesion in lesion_stats:
                    lesion_stats[lesion] = []
                lesion_stats[lesion].append(statistics.mean(vals))

            output_data.append([os.path.basename(f).split("~")[0], lesion, *printvals, *vals])

    ofile = sys.stdout
    if args.output_csv is not None:
        ofile = open(args.output_csv, 'w')

    for line in output_data:
        print(*line, sep=",", file=ofile)

    if args.output_csv is not None:
        ofile.close()
        print("Output written to", args.output_csv)
        print("All done! Have a nice day :)")

# EOF
